site_name: MacArthur HAT v1.2 Documentation
use_directory_urls: false
site_dir: MacArthur_HAT_docs_download
theme:
  name: readthedocs
markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Header pinout: pinout.md
  - Mounting the HAT: mounting.md
  - Power management: power.md
  - MAIANA AIS: maiana.md
  - NMEA 2000: nmea2000.md
  - NMEA 0183: nmea0183.md
  - Seatalk<sup>1</sup> - input: seatalk.md
  - Seatalk<sup>1</sup> - alternative uses: seatalkalt.md
  - 1-Wire - sensors: 1w.md
  - 1-Wire - alternative uses: 1walt.md
  - I2C - sensors: i2c.md
  - Credits: credits.md
  - Download these docs: download.md